name: flutter_startup_kit
description: Generate production-ready Flutter apps with Clean Architecture, Bloc, and enterprise-grade standards.
version: 1.0.0
homepage: https://github.com/LadeedAhamed/flutter_startup_kit
repository: https://github.com/LadeedAhamed/flutter_startup_kit
issue_tracker: https://github.com/LadeedAhamed/flutter_startup_kit/issues

environment:
  sdk: ^3.0.0

executables:
  flutter_startup_kit:

dependencies:
  args: ^2.4.0

dev_dependencies:
  test: ^1.24.0
